nuxt.config.ts

#23 
- #23 
- googleSearchConsoleの所有権用タグをアナリティクス用のアカウントで生成したものに変更。

googleSearchConsoleのプロパティをアナリティクス用のアカウント用に作り直した。

---

README.md
nuxt.config.ts
package.json

- #40
- header等が公認版になっていなかったため修正

header等が公認版になっていなかったため修正

---

components/SideNavigation.vue
components/cards/ConfirmedCasesAttributesCard.vue
components/cards/ConfirmedCasesNumberCard.vue
components/cards/ConsultationDeskReportsNumberCard.vue
components/cards/TestedNumberCard.vue

リンクが古いものを更新1

---

components/SideNavigation.vue

ライセンス表記が東京のままになっていたので修正

---

nuxt.config.ts
pages/index.vue
store/data.js

- #53 
- nishidayoshikatsu/covid19-yamaguchi-opendata#8
- news.jsonを外部ファイルから読み込めるようにした

news.jsonを外部から読み込めるように変更

---

pages/index.vue

- #53 
- nishidayoshikatsu/covid19-yamaguchi-opendata#8
- news.jsonを外部ファイルから読み込めるようにした

データが正常に表示されない問題を修正

---

components/SideNavigation.vue

リンク切れを起こしている部分を新しいリンクに変更

---

components/DataView.vue

- close #62 
- #62 
- 出典をわかりやすく明記した

出典をわかりやすく明記した

---

components/WhatsNew.vue

緊急事態宣言のリンクを更新

---

components/cards/YamaguchiMapCard.vue

地図カードのタイトルを「市区町村別陽性患者の累計」に変更

---

components/cards/YamaguchiMapCard.vue

地図データの出典を記載

---

components/SideNavigation.vue
components/WhatsNew.vue
pages/parent.vue

- #58 
- 一部リンクが切れていたものを修正
- コンテンツの内容を再び見直し修正

コンテンツのアップデート

---

pages/about.vue

- close #50 
- データについての記述を「当サイトについて」に追記

データについての記述を追記

---

components/cards/TestedNumberCard.vue
nuxt.config.ts

- close #113 
- pcr検査件数データをpcr検査人数データへ変更

pcr検査実施件数データをpcr検査人数データに変更 fix #113

---

components/SideNavigation.vue

i18nの機能を一時的に停止

---

components/SideNavigation.vue

知事メッセージのリンクを修正 #123

---

nuxt-i18n.config.ts

enページが残っている問題を修正

---

nuxt.config.ts

- close #116 
- enページが生成されないように設定

enページが生成されないよう修正

---

components/cards/ConfirmedCasesAttributesCard.vue
yarn.lock

- #144 
- 陽性患者の属性データの単位を人から例に変更

陽性患者の属性データの単位を人から例に変更

---

assets/variables.scss
components/ConfirmedCasesDetailsTable.vue
components/DataView.vue
components/MenuList.vue
components/ScrollableChart.vue
components/StaticCard.vue
components/TimeBarChart.vue
components/flow/FlowPc.vue
components/flow/FlowPcAdvisory.vue
components/flow/FlowPcDays.vue
components/flow/FlowPcNotRequired.vue
components/flow/FlowPcPast.vue
components/flow/FlowPcPcr.vue
components/flow/FlowPcRequired.vue
components/flow/FlowPcSuspect.vue
components/flow/FlowSpAccording.vue
components/flow/FlowSpAdvisory.vue
components/flow/FlowSpPast.vue
components/flow/flow_sp.scss
layouts/default.vue
nuxt.config.ts
pages/flow.vue
pre-commit.sh
utils/colors.ts
utils/formatDate.ts
utils/formatDayBeforeRatio.ts
utils/formatGraph.ts
utils/monitoringStatusValueFormatters.ts
utils/tab-event-bus.ts

- #134 
- すべてのグラフにおいて、一定以上のデータがある場合、スクロールできるようにし、各日のデータを見やすくする

グラフスクロールを追加

---

assets/variables.scss
components/DataTable.vue

- #150 
- 陽性患者の属性の表のフォントサイズ等を調整

表のレイアウトを見やすいように調整

---

assets/variables.scss
components/WhatsNew.vue

- #137
- 最新のお知らせにtwitterのバナーを表示した

最新のお知らせにtwitterのバナーを表示

---

assets/variables.scss
components/WhatsNew.vue

- #137 
- [twitterのガイドライン](https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf)通りに配色を変更しました

twitterのガイドライン通りに配色を変更

---

nuxt.config.ts

- #164 
- #163 
- nuxt.jsのアップデートに伴い、targetプロパティが追加された。それに伴い、modeプロパティの使用を廃止し、targetプロパティへの変更を行った。

modeプロパティを廃止し、targetプロパティを追加する

---

components/ConfirmedCasesDetailsTable.vue

- close #169 
- #169 
- 検査陽性者の状況カードのレイアウトを変更した．

検査陽性者の状況カードのレイアウトを変更

---

assets/locales/ja.json
components/cards/ConfirmedCasesAttributesCard.vue
utils/formatTable.ts

- close #179 
- 陽性患者の属性の公表日の形式を`YYYY/MM/DD`に変更
- 陽性患者の属性のNoの形式を`xx例目`に変更

陽性患者の属性の公表日に年情報を追加

---

components/cards/ConfirmedCasesAttributesCard.vue

- close #185 
- 陽性患者の属性の右上の数値をテーブルのはじめのNoからとるようにした

陽性患者の属性の右上の数値を正しいものに変更

---

package.json

- close #191 
- precommit.shを削除したので、利用しないように実行スクリプトを変更

precommit.shをcommit時に実行しないよう変更

---

cert_check/cert_check.sh
cert_check/setting.sh

- ~~close~~#171 
- #164 
- #163 
- 証明書の期限切れを検知して通知するスクリプトを追加

証明書のチェック機能を追加した

---

.github/workflows/link_check.yml
link_check/main.sh

- #123 
.github/workflow/link_check.yml
link_check/main.sh
workflowが機能していなかったため修正．
また，念のためログ出力をするようにした．

link_check workflowの修正とログ出力を行うようにした．

---

components/SideNavigation.vue

Go To Eatのリンクを山口県広報広聴課 公式チャンネルの下に追加した。
- close #168 
- Go To Eatのリンクを山口県広報広聴課 公式チャンネルの下に追加した。
- https://gotoeat-yamaguchi.com/use/

Go To Eatのリンクを移動

---

pages/otherpref.vue

- close #194
- #194 
- 下記リンクを変更
1. 京都府
1. 秋田県
1. 栃木県
1. 山梨県
1. 滋賀県
1. 徳島県
1. 宮崎県

リンク切れになっている他県リンクを修正 ( 7links

---

assets/locales/en.json

flowページの未翻訳部分を追加

---

pages/otherpref.vue

- close #216 
- 福岡県版のリンクを公式のものに変更

福岡県版のサイトがcloseするのでリンクを変更

---

components/CocoaRedirectCard.vue

- #218 
- アプリボタンの位置が崩れないよう変更しました

アプリボタンの位置を調整

---

layouts/default.vue

- close #222 
- google search consoleの設定を追加

google search consoleの設定を追加

---

components/cards/ConfirmedCasesAttributesCard.vue
components/cards/ConfirmedCasesDetailsCard.vue

- close #200 
- #200 
- `ConfirmedCasesDetailsCard`内の不要な console statement の削除
- `ConfirmedCasesAttributesCard`の日付のフォーマットの変更

日付のフォーマットの統一

---

components/cards/ConfirmedCasesAttributesCard.vue

- close #227 
- 陽性患者の属性のNoのソートバグを修正

陽性患者の属性のNoのソートバグを修正

---

.github/workflows/link_check.yml
link_check/main.sh
link_check/setting.sh

- #123 
- ローカルではdotenv
- github secretで管理

ci: webhookURLをsecretに管理

---

.github/workflows/cert_check.yml
.github/workflows/link_check.yml
cert_check.sh
cert_check/main.sh
cert_check/setting.sh
link_check.sh

- #171 
- env, github secretで管理
- actionsを追加

ci: 定期的にssl証明書の期限を確認

---

pages/parent.vue

style: リンク切れのものを更新

---

nuxt-i18n.config.ts
nuxt.config.ts

- #249 
- nuxt.config.tsとnuxt-i18n.config.tsの設定を最適化

perf: configファイルを修正
